<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Jour</name>
   <tag></tag>
   <elementGuidId>6d6e74d4-99ef-40d4-9ab6-b19311a6b80f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/app-root/main/app-registration/div/div[3]/app-identification/form/div[2]/app-date[2]/fieldset/div[2]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
