<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_CertainesInformationsSaisiesSontIncorrectes</name>
   <tag></tag>
   <elementGuidId>cd34fc86-f3f2-4c9a-96d7-1a43025157ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
