<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_SolliciteTS_TS-PT-FrenchTechVisaForFounders</name>
   <tag></tag>
   <elementGuidId>ef48ae4f-4842-4923-9019-6dd3cb2c2558</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/app-portal/main/app-theme-v2/div/app-triage-intermediaire/div/div/div/form/div/div[3]/p-radiobutton/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
