<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_SolliciteTS_MembreDeFamillePasseportTalent_EnfantEtJeuneMajeur</name>
   <tag></tag>
   <elementGuidId>fbcab088-10a1-40e1-912a-d8f4f036fb30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-triage-intermediaire/div/div/div/form/div/div[2]/p-radiobutton/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
