<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_SolliciteTS_ProtectionInternationale</name>
   <tag></tag>
   <elementGuidId>7636f62a-4342-4a1f-8b09-2eba6bb2a5ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/div[4]/app-radio-tree-button/div/p-radiobutton/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
