<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_SolliciteTS_InvestisseurOuPorteurProjetEconomique</name>
   <tag></tag>
   <elementGuidId>e7ddcdc8-5a9e-4732-bc32-fa85832cda53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/form/div[1]/div[2]/fieldset/div[3]/app-radio-tree-button/div/div/div[3]/app-radio-tree-button/div/p-radiobutton/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
