<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_SolliciteTS_MotifHumanitaire</name>
   <tag></tag>
   <elementGuidId>9caa1ce5-177f-4cbb-874d-7d93cedceb39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/div[10]/app-radio-tree-button/div/p-radiobutton/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
