<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_SolliciteEtudiant</name>
   <tag></tag>
   <elementGuidId>d490024c-7368-434c-bbd0-60389df22035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/app-triage/div/div/div/form/div[1]/div[2]/fieldset/div[1]/app-radio-tree-button/div/p-radiobutton/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
