<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_SolliciteTS_TS-PT-FrenchTechVisaForInvestors</name>
   <tag></tag>
   <elementGuidId>16426d3e-bb9e-4120-bc8f-d9d75d00ff07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/app-portal/main/app-theme-v2/div/app-triage-intermediaire/div/div/div/form/div/div[1]/p-radiobutton/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
