<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AccepterLeDocumentSignature</name>
   <tag></tag>
   <elementGuidId>453ef3ff-7a99-4081-9064-3683d14239b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/app-etat-civil/div/div[2]/div/app-justificatifs[2]/div/div[2]/div/div[2]/anef-input-radio/div/div/fieldset/div/div[2]/p-radiobutton/div/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
