<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AccepterLeDocumentPasseport</name>
   <tag></tag>
   <elementGuidId>272ea448-01b9-4891-9f76-39bcc106a30d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/app-etat-civil/div/div[2]/div/app-justificatifs[3]/div/div[2]/div/div[2]/anef-input-radio/div/div/fieldset/div/div[2]/p-radiobutton/div/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
