<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_RejeterLeDocumentPhotographie</name>
   <tag></tag>
   <elementGuidId>f7c4db84-3630-4c1c-a1ea-e1a695d124ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/app-etat-civil/div/div[2]/div/app-justificatifs[1]/div/div[2]/div/div[3]/anef-input-radio/div/div/fieldset/div/div[1]/p-radiobutton/label
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
