<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_RejeterLeDocumentSignature</name>
   <tag></tag>
   <elementGuidId>8415d786-e42c-47be-913a-3cb8d66ecd2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/app-etat-civil/div/div[2]/div/app-justificatifs[2]/div/div[2]/div/div[2]/anef-input-radio/div/div/fieldset/div/div[1]/p-radiobutton/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
