<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_RejeterLeDocumentCopieTitreSejour</name>
   <tag></tag>
   <elementGuidId>9bf1c12e-750a-4008-9967-18e0a93e54e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/app-etat-civil/div/div[2]/div/app-justificatifs[4]/div/div[2]/div/div[2]/anef-input-radio/div/div/fieldset/div/div[1]/p-radiobutton/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
