<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_RejeterLeDocumentPasseport</name>
   <tag></tag>
   <elementGuidId>89789edc-e80f-43fb-b34d-ce60f7b6f81a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/app-etat-civil/div/div[2]/div/app-justificatifs[3]/div/div[2]/div/div[2]/anef-input-radio/div/div/fieldset/div/div[1]/p-radiobutton/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
