<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Check_DocManquantPasseport</name>
   <tag></tag>
   <elementGuidId>fe21c3bd-c166-45d8-bf3f-da8cefbe183c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/app-etat-civil/div/div[2]/div/app-justificatifs[3]/div/div[1]/anef-input-check/div/div/p-checkbox/div/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
