<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ConfirmerNEtrangerConjoint</name>
   <tag></tag>
   <elementGuidId>13c1c279-60ce-4679-b994-8526887f8295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-informations-membre-famille-generic/div/div[5]/div/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
