<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_confirmerNombreDeComptes</name>
   <tag></tag>
   <elementGuidId>ec7aae28-9293-4efa-8344-990e1a6202cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-createur-entreprise//app-moyens-financiers/div[2]/div/anef-repeat-form/div/div/div[2]/button/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
