<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_EntrepriseInnovanteReconnueOganismePublic</name>
   <tag></tag>
   <elementGuidId>ddeb44d8-efff-4632-a7e0-3700fe27bce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-accordiontab-3-content&quot;]/div/div/div[2]/div/div/div/app-indent-wrapper/app-informations-relatives-activite-pro/div/div/div[1]/div/p-radiobutton/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
