<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_EntrepriseANumeroSiret</name>
   <tag></tag>
   <elementGuidId>e9f2e32f-b1d7-4564-810b-0c3345750919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-createur-entreprise//app-informations-relatives-entreprise-creee/div/div/div[1]/div/div/p-radiobutton/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
