<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_NePasVivreEnPolygamie</name>
   <tag></tag>
   <elementGuidId>e122278b-b8af-4bf9-bb4a-a466b8066e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-demande-visiteur//app-motif-sejour-visiteur//p-accordiontab[1]/div[2]/div/div/div[2]/anef-input-check/div/div/p-checkbox/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
