<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_ContratMandataire_Salarie</name>
   <tag></tag>
   <elementGuidId>347577e2-e24c-4155-abe2-9af671e33855</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-contrat-travail-ptinv/div/div[1]/div/anef-input-radio/div/div/fieldset/div/div[1]/p-radiobutton/div/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
