<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_TypeContratMandataireCDI_Salarie</name>
   <tag></tag>
   <elementGuidId>e47e62a6-cb15-45fe-af2b-aa0420e6e7e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-contrat-travail-ptinv/div/div[2]/div/div/anef-input-radio/div/div/fieldset/div/div[1]/p-radiobutton/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
