<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_ActivitesSoumisesAutorisationExercice_Non</name>
   <tag></tag>
   <elementGuidId>08124b0f-6e02-4f97-979a-71f84d1bed3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-createur-entreprise/div/app-indent-wrapper/app-informations-relatives-entreprise-creee/div/div/div[5]/div/anef-input-radio/div/div/fieldset/div/div[2]/p-radiobutton/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
