<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click-select_DateFinContrat_MM</name>
   <tag></tag>
   <elementGuidId>d754dbea-4012-4630-a58c-3a182bda25f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]//div[2]//div[2]//div[1]//app-contrat-travail//div[3]//div[2]//*[@id=&quot;MOIS&quot;]/div/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
