<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NEtrangerConjoint</name>
   <tag></tag>
   <elementGuidId>1890a0c3-6f79-4436-ac1f-daa91937bb85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-informations-membre-famille-generic/div/div[4]/div/anef-input-text/div/div/div[1]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
