<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OrganismeDAccueil</name>
   <tag></tag>
   <elementGuidId>b9cdfee1-1618-4729-ac0e-a09a0e794f74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/app-portal/main/app-theme-v2/div/app-demande-ptch/div/div[3]/app-motif-sejour-ptch/div[2]/div/p-accordion/div/form/p-accordiontab/div[2]/div/app-information-relatives-activite-recherche/div[1]/div/anef-input-text/div/div/div[1]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
