<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_DateFinContrat_AAAA</name>
   <tag></tag>
   <elementGuidId>cfe53965-e97a-4b9d-a14d-96d40560ecef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div[1]/div/div/div/app-indent-wrapper/app-contrat-travail/div/div[3]/div/anef-input-date/div/div/fieldset/div/div[3]/div/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
