<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateDeNaissanceConjoint_JJ</name>
   <tag></tag>
   <elementGuidId>1f7ad894-e556-49c1-94fd-4c72677480ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-informations-membre-famille-generic/div/div[3]/div/anef-input-date-approx/div/div/fieldset/div[1]/div[1]/div/div/input|//app-situation-familiale/div[2]/div/anef-input-date-approx/div/div/fieldset/div/div[1]/div/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
