<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FonctionExerceeDansLaSociete</name>
   <tag></tag>
   <elementGuidId>8b67eccc-f1c0-48b3-b2b4-82fb01e2f9ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-demande-ptinv//app-motif-sejour-ptinv//div/app-createur-entreprise//app-informations-relatives-entreprise-creee/div/div/div[6]/div/anef-input-text/div/div/div[1]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
