<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_DateFinContrat_JJ</name>
   <tag></tag>
   <elementGuidId>5a815080-8d74-4d54-937d-6d97f2d189f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-contrat-travail/div/div[3]/div/anef-input-date/div/div/fieldset/div/div[1]/div/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
