<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Domaine</name>
   <tag></tag>
   <elementGuidId>e5cb1d28-fbca-4eba-b2fd-1c23565b3b27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-motif-sejour-ptart//app-indent-wrapper/app-informations-artiste-non-salarie/div/div[1]/div/anef-input-text/div/div/div[1]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
