<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateDeNaissanceConjoint_MM</name>
   <tag></tag>
   <elementGuidId>26c04476-47f7-4cb0-a3ba-b3bfe13f0519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-informations-membre-famille-generic/div/div[3]/div/anef-input-date-approx/div/div/fieldset/div[1]/div[2]/div/div/p-dropdown/div/div[3]/label|//app-situation-familiale/div[2]/div/anef-input-date-approx/div/div/fieldset/div[1]/div[2]/div/div/p-dropdown/div/div[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
