<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NSiretGROUPE</name>
   <tag></tag>
   <elementGuidId>da6bebdb-fa6c-48b4-a127-8ca414bdab2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-motif-sejour-ptinv//app-informations-groupe-ptinv/div/div[2]/div/anef-input-text/div/div/div[1]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
