<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SiteInternet</name>
   <tag></tag>
   <elementGuidId>eb692c77-ce68-47fa-b7aa-e87c900d4f6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-demande-ptinv//app-informations-groupe-ptinv/div/div[3]/div/anef-input-text/div/div/div[1]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
