<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PrenomConjoint</name>
   <tag></tag>
   <elementGuidId>df123019-edcf-447b-b81e-c23035eab310</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-demande-fampt//app-motif-sejour-fampt//app-informations-membre-famille-generic/div/div[2]/div/div/app-prenoms-selector/div/div[1]/fieldset/div/app-prenom/div/div/anef-input-text/div/div/div[1]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
