<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_CycleEtudes</name>
   <tag></tag>
   <elementGuidId>089911d6-797b-47f1-a5fa-0b785d3b6688</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;CYCLE_ETUDES&quot;]/div/div[5]/div/ul/p-dropdownitem[4]/li/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
