<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_NiveauEtudesEnFinDAnnee</name>
   <tag></tag>
   <elementGuidId>4b0edb23-959b-4c0f-9980-7335789879f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;NIVEAU_ETUDES&quot;]/div/div[5]/div/ul/p-dropdownitem[4]/li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
