<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Value_Mois_TypeDeContratCDI</name>
   <tag></tag>
   <elementGuidId>45621e0c-3826-4ae6-b5d2-90ebd509458f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;MOIS&quot;]/div/div[5]/div/ul/p-dropdownitem[4]/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
