<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Value_SituationFamiliale</name>
   <tag></tag>
   <elementGuidId>0707be47-4c2e-4d98-a7a7-8cd258eabaeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-situation-familiale/div/div/anef-input-select/div/div/p-dropdown/div/div[5]/div/ul/p-dropdownitem[2]/li/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
