<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Value_PaysUnion</name>
   <tag></tag>
   <elementGuidId>3778684c-955e-4621-b373-c7a07ed70769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;PAYS_UNION&quot;]/div/div[5]/div/ul/p-dropdownitem[76]/li/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
