<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Value_MotifChangementSituation</name>
   <tag></tag>
   <elementGuidId>706e8f7c-895d-4df9-b2ae-51604708fb68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;SITUATION_PVD&quot;]/div/div[5]/div/ul/p-dropdownitem[4]/li/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
