<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PaysUnion</name>
   <tag></tag>
   <elementGuidId>785d2bbd-0464-4ee6-8157-bf9012ea79f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-situation-familiale/div[3]/div/anef-input-select/div/div/p-dropdown/div/div[4]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
