<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SituationFamiliale</name>
   <tag></tag>
   <elementGuidId>7cd8cf95-9d4f-4af5-957c-4b61ad491208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-situation-familiale/div/div/anef-input-select/div/div/p-dropdown/div/div[4]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
