<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DateFinContrat_MM</name>
   <tag></tag>
   <elementGuidId>99d8d280-0469-42b5-98fb-adc62af476d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]//div[2]//div[2]//div[1]//app-contrat-travail//div[3]//div[2]//*[@id=&quot;MOIS&quot;]/div/div[5]/div/ul/p-dropdownitem[3]/li/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
