<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DemandeAutorisationDeTravail</name>
   <tag></tag>
   <elementGuidId>5b8c2afb-ba06-4ee6-bef2-36d761e08a9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/div/div/anef-tile[3]/a/span/span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
