<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_ProlongerRenouvellementMonTitre</name>
   <tag></tag>
   <elementGuidId>db801ba6-11a9-46d1-83cf-1ec0e2ea37bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-triage-intermediaire-pvd//anef-input-radio//div[1]/p-radiobutton/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
