<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_ChangementSituation</name>
   <tag></tag>
   <elementGuidId>9d489b84-7ca0-43c2-b45d-d6d1be24ebcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-declaration-changement//anef-input-radio//div[1]/p-radiobutton/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
