<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verif_PopUpVotreTitreDeSejourEstExpireDepuis9Mois</name>
   <tag></tag>
   <elementGuidId>4c2142ae-5acb-4434-aa7d-47aec99cfeb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/app-portal/main/app-theme-v2/div/app-triage/div/div/div/form/div[1]/div/p-message/div/span[2]/strong[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
