<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_ChoisirFichier_SouscriptionAssurance</name>
   <tag></tag>
   <elementGuidId>e904ed4d-2a05-4d5b-acb7-557f50d081f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-demande-visiteur//app-justificatifs-visiteur//p-accordiontab[2]/div[2]/div/app-justificatif-assurance-maladie/div/app-pieces-jointes/div/span[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
