<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_ChoisirFichier_DiplomeObtenuEnFrance</name>
   <tag></tag>
   <elementGuidId>70ccadc5-dde2-4e49-ba7c-1709c5d6f91b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-justificatifs-visiteur//p-accordiontab[2]//div[2]/app-pieces-jointes//span[1]/input|//app-justificatifs-ptsq//p-accordiontab[2]//div[2]/app-pieces-jointes//span[1]/input|//app-justificatifs/div[2]/div/p-accordion/div/p-accordiontab[2]/div[2]/div/app-pieces-jointes[3]/div/span[1]/input|//div/div/app-justificatif-diplome-chercheur/div/app-pieces-jointes/div/span[1]/input
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
