<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_ChoisirFichier_AssuranceMaladie</name>
   <tag></tag>
   <elementGuidId>833ba96f-477f-49ab-8c4b-29fd1be584c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-justificatifs-visiteur//app-justificatif-assurance-maladie//app-pieces-jointes//span[1]/input|//app-justificatifs-ptsq//app-justificatif-assurance-maladie//app-pieces-jointes//span[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
