<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tab_tr1NumDemande</name>
   <tag></tag>
   <elementGuidId>9055d746-51fd-4965-aeb3-51d41f4458b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/app-demandes-sejour/div/div[2]/app-demande-table/div[2]/p-table/div/div/table/tbody/tr/*/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
