<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_SuiviDemandeNumEtranger</name>
   <tag></tag>
   <elementGuidId>3fa9bd92-5745-45de-bfab-ac29aae1427e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/app-ma-demande-sejour/div[1]/table/tbody/tr[1]/td[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
