<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ValiderAdresseRapatrierLeDossier</name>
   <tag></tag>
   <elementGuidId>68c0526e-ef8b-4652-8545-a17708570f13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/app-demande-instruction/div/div[2]/div[2]/div/button[3]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
