<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_PopUpAttestationProlongationAnnuler</name>
   <tag></tag>
   <elementGuidId>e0d57d2e-1366-495c-9749-cc3b1dbb09ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/app-demande-instruction/div/app-statut-demandeur/div/div/div[3]/p-dialog/div/div[3]/p-footer/button[1]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
