<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_PopUpCommentaireFermer</name>
   <tag></tag>
   <elementGuidId>1617f4c9-2adf-4429-a995-e0d345a40ba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/app-demande-instruction/div/app-statut-demande/div/div/lib-generic-modal/p-dialog/div/div[3]/p-footer/button/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
