<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_AttestationProlongation</name>
   <tag></tag>
   <elementGuidId>282b9ddf-8a65-46c5-bcb7-f6fe263d3ea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/app-demande-instruction/div/app-statut-demandeur/div/div/div[3]/div[3]/div/button/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
