<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_TypeDocument</name>
   <tag></tag>
   <elementGuidId>f3a9e7fb-d208-45e0-86ab-063652df8589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-layout/div/div/div/app-navigation-layout/div[2]/app-demande-instruction/div/app-statut-demande/app-documents-additionnels/lib-generic-modal/p-dialog/div/div[2]/div[3]/p[2]/anef-input-select/div/div/p-dropdown/div/div[3]/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
