<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_TypeAction</name>
   <tag></tag>
   <elementGuidId>6b202a5a-32b7-4f8d-96ec-516e0e6266fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/app-demande-instruction/div/app-statut-demande/app-historique-demande/lib-generic-modal/p-dialog/div/div[2]/div/div[1]/input-multi-select/div/div/p-multiselect/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
