<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_DesEnfantsACharge_Non</name>
   <tag></tag>
   <elementGuidId>1852914f-7fe3-4967-b8c0-94a5245369a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-demande-ptsq//app-informations-personnelles-shared//app-has-enfants-charge//div//fieldset/div/div[2]/p-radiobutton/div/div[2]/span|//app-demande-visiteur//app-informations-personnelles-shared//app-has-enfants-charge/div/div/anef-input-radio/div/div/fieldset/div/div[2]/p-radiobutton/div/div[2]/span|//app-demande-ptch//app-informations-personnelles-shared//app-has-enfants-charge/div/div/anef-input-radio/div/div/fieldset/div/div[2]/p-radiobutton/div/div[2]/span|//div/app-has-enfants-charge/div/div/anef-input-radio/div/div/fieldset/div/div[2]/p-radiobutton/div/div[2]/span
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
