<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_liensPersonnelsFamiliaux_2_Non</name>
   <tag></tag>
   <elementGuidId>c1a2cafe-9414-40ba-a30c-74f022b58449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-accordiontab-1-content&quot;]/div/div/div[2]/div/anef-input-radio/div/div/fieldset/div/div[2]/p-radiobutton/div/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
