<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_AdresseUsager</name>
   <tag></tag>
   <elementGuidId>381b0aae-bf98-4cfa-8200-a6deb1788e65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-informations-personnelles//app-adresse-etalab//app-vls-ts-etalab//div/input|//app-informations-personnelles-shared//app-adresse-etalab//app-vls-ts-etalab//div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/app-root/div/app-portal/main/app-theme-v2/div/app-demande/div/div[3]/app-informations-personnelles/div[2]/div/p-accordion/div/form/p-accordiontab[3]/div[2]/div/app-adresse-etalab/div[1]/app-vls-ts-etalab/div/div/div/input</value>
      <webElementGuid>a9f35db0-0457-49ee-9bbd-ae321f4f1c02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
